package com.zimplyshop.app.extras;

/**
 * Created by praveen goel on 10/8/2015.
 */
public interface ZAppConstants {
    int Z_PRODUCT_DESCRIPTION_PRODUCT_RATING_LIST_TYPE_HEADER = 0;
    int Z_PRODUCT_DESCRIPTION_PRODUCT_RATING_LIST_TYPE_ITEM = 1;
    int Z_PRODUCT_DESCRIPTION_PRODUCT_RATING_LIST_TYPE_LOADING = 2;

    int Z_ADD_TO_WISHLIST_START_ACTIVITY_FOR_RESULT_REQUEST = 1;

    int Z_CART_LIST_TYPE_FOOTER = 1;
    int Z_CART_LIST_TYPE_PRODUCT = 2;
}
